# golangci-lint configuration for zen-sdk
# Compatible with golangci-lint v1.x (CI builds from source which may be v1)

run:
  timeout: 5m
  tests: true
  go: "1.25"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic
