linters-settings:
  gofmt:
    simplify: true
  govet:
    enable:
      - shadow
  errcheck:
    check-type-assertions: true
    check-blank: true
  gosimple:
    checks: ["all"]
  staticcheck:
    checks: ["all"]
  # unused settings removed - no longer supported in latest golangci-lint
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - gocritic

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - errcheck
        - gocritic
  max-issues-per-linter: 0
  max-same-issues: 0
